name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SimpleString test
      id: simplestring-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SimpleString test
        setup-command: ''
        command: make test
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SIMPLESTRING-TEST_RESULTS: "${{steps.simplestring-test.outputs.result}}"
      with:
        runners: simplestring-test
